services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3020:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - HOST=0.0.0.0
